### ISSUE TITLE
Remove unused fields in api/User/getuserdetails response object

### ISSUE THREAD

**Issue by sarveny** [RMacWilliam/permitsadmin#1]
Remove unused fields in response object:

{
    firstName: string;
    initial: string;
    lastName: string;
    addressLine1: string;
    addressLine2: string;
    city: string;
    province: IParentKeyValue;
    postalCode: string;
    country: IKeyValue;
    telephone: string;
    email: string;

    adminUser: boolean;

    // Are these needed for the UI?
    changeEmailAttempts: number;
    currentSeasonLogins: number;
    logins: number;
    verified: boolean;

    contactConsent: boolean;
    magazine: boolean;
    magazine1: boolean;
    origContactId: number; // TODO: Is the type correct?
    volunteerStatus: number; // TODO: Is the type correct?
}

**Comment by RMacWilliam** [comment]
6 fields removed that won't be used in most cases - we can worry about the special cases later (changing email).  Will double check that the Magazine fields are no longer needed, so this may change a bit, but currently here is the new structure:
{
  "email": "string",
  "firstName": "string",
  "lastName": "string",
  "telephone": "string",
  "verified": true,
  "initial": "string",
  "contactConsent": true,
  "adminUser": true,
  "volunteerStatus": 0,
  "addressLine1": "string",
  "addressLine2": "string",
  "city": "string",
  "postalCode": "string",
  "province": {
    "country": "string",
    "key": "string",
    "value": "string"
  },
  "country": {
    "key": "string",
    "value": "string"
  }
}

**Comment by sarveny** [comment]
Updated UI with changes.
