### ISSUE TITLE
Create api to fetch shipping types

### ISSUE THREAD

**Issue by sarveny** [RMacWilliam/permitsadmin#10]
Array of shipping types should have following fields:

export interface IShippingMethod {
    id: string; // guid
    name: string;
    price: number;
    showConfirmation: boolean;
}

* showConfirmation=true shows user the shipping confirmation dialog box.

For example:
[
    {
        id: "73cd7359-acc1-4c64-a691-6668586a4f27",
        name: "Standard",
        price: 0,
        showConfirmation: true
    },
    {
        id: "3744e5d4-3012-4c05-809d-4d8db59c8fe8",
        name: "Tracked",
        price: 10,
        showConfirmation: false
    }
]

**Comment by RMacWilliam** [comment]
Done.  A little bit of extra logic needed here - explained in Teams.

**Comment by sarveny** [comment]
Added api to app code.
