### ISSUE TITLE
Add email to api/user/validateuser result

### ISSUE THREAD

**Issue by sarveny** [RMacWilliam/permitsadmin#12]
Please include email in the validateuser result.

Also, do you save language on the backend? If so, it could also be retrieved with the login result.

**Comment by RMacWilliam** [comment]
Email added.  And yeah, let's discuss how we want to store language preferences.  The old system did it with cookies, but we don't have to do it that way again necessarily.

**Comment by sarveny** [comment]
Updated UI to use email returned from /validateuser api.
