### ISSUE TITLE
Obfuscate and remove fields api/Vehicle/getvehiclesandpermitsforuser

### ISSUE THREAD

**Issue by sarveny** [RMacWilliam/permitsadmin#13]
Obfuscate VehicleId in api/Vehicle/getvehiclesandpermitsforuser.
Remove OwnerId in api/Vehicle/getvehiclesandpermitsforuser.
Obfuscate PermitId in api/Vehicle/getvehiclesandpermitsforuser.

**Comment by RMacWilliam** [comment]
Done, but the original PermitId in the permits collection will stay there just temporarily - you should ignore it - needs a little refactor to remove as it's used elsewhere in the business logic, but I will refactor ASAP - consider it gone.

**Comment by sarveny** [comment]
Updated app with changes.
