### ISSUE TITLE
Make changes in api/Vehicle/getvehiclesandpermitsforuser

### ISSUE THREAD

**Issue by sarveny** [RMacWilliam/permitsadmin#15]
Change type of clubId in permits object to be { key, value} instead of integer.
Remove vehicleId in permits object.
Remove permitId in permits object.

Change type of permitTypeId in permits object to be { key, value, valueFr } instead of integer.

Add permitSelections property in vehicle object to be of type:

interface IDefaultPermit {
    oPermitId: string;
    permitOptionId: number;
    dateStart: Date;
    dateEnd: Date;
    clubId: string;
}

Note: When UI send request to persist data, it will send:

{
   oVehicleId: string,  // existing vehicle
   oPermitId: string, // guid
   permitOptionId: number;
   dateStart: Date;
   dateEnd: Date;
   clubId: string;
}

**Comment by sarveny** [comment]
Just confirming that oPermitId in permitSelections is set to a guid when it's returned from the api and the same GUID is returned each time.

**Comment by RMacWilliam** [comment]
Ah - probably not the same GUID being returned as the entire object is recreated - if you need the same GUID's I should be able to find a way to keep them.  Thinking...

**Comment by sarveny** [comment]
Updated app with changes.
