### ISSUE TITLE
Add editable flag for each snowmobile/vehicle returned by api/vehicle/getvehiclesandpermitsforuser

### ISSUE THREAD

**Issue by sarveny** [RMacWilliam/permitsadmin#18]
For each snowmobile/vehicle, please return flag indicating if the vehicle is editable.

Editable vehilcles will have Edit and Delete buttons.
Non-editable vehicles will have an [i] icon that will display a popup message "This vehicle cannot be modified as a Ministry of Transportation Ontario Snowmobile Trail Permit has been registered to it.".

**Comment by RMacWilliam** [comment]
Done

**Comment by sarveny** [comment]
New field included in app code.
