### ISSUE TITLE
Create api to persist permitSelections from UI interaction

### ISSUE THREAD

**Issue by sarveny** [RMacWilliam/permitsadmin#19]
Create (post) api to save permit selections for when user is selecting permit options for each vehicle:

The UI will call api and pass following info:

interface IApiGetVehiclesAndPermitsForUserPermitSelections {
    oVehicleId?: string; <-- I will send obfuscated ID of vehicle
    oPermitId?: string; <-- this is set by API currently, I will send it back
    permitOptionId?: number;
    dateStart?: Date;
    dateEnd?: Date;
    clubId?: string; <-- this is the ID that comes from key/value pair
}

Then, modify api/Vehicle/getvehiclesandpermitsforuser to return this information if exists.

**Comment by RMacWilliam** [comment]
Done.

**Comment by sarveny** [comment]
Added api to app.

**Comment by sarveny** [comment]
On success, please return values for:
{
"oVehicleId": string,
	"oPermitId": string,
    "permitOptionId": number,
    "dateStart": Date,
    "dateEnd": Date,
    "clubId":number
}

**Comment by RMacWilliam** [comment]
Done.

**Comment by sarveny** [comment]
Api has been added to app code.
