### ISSUE TITLE
Rename field in province object in api/User/getuserdetails response

### ISSUE THREAD

**Issue by sarveny** [RMacWilliam/permitsadmin#2]
Province will use IParentKeyValue interface. This can be used for hierarchical data.

Please rename "country" field in province property to "parent".

Before:
province: {
    country: string;
    key: string;
    value: string;
}

After:
export interface IParentKeyValue {
    parent: string;
    key: string;
    value: string;
}

**Comment by RMacWilliam** [comment]
This is complete in the user data object, but will also be used generally going forward:
{
  "email": "string",
  "firstName": "string",
  "lastName": "string",
  "telephone": "string",
  "verified": true,
  "initial": "string",
  "contactConsent": true,
  "adminUser": true,
  "volunteerStatus": 0,
  "addressLine1": "string",
  "addressLine2": "string",
  "city": "string",
  "postalCode": "string",
  "province": {
    "**parent**": "string",
    "key": "string",
    "value": "string"
  },
  "country": {
    "key": "string",
    "value": "string"
  }
}

**Comment by sarveny** [comment]
Updated UI with changes.
