### ISSUE TITLE
Create API to add/edit vehicle

### ISSUE THREAD

**Issue by sarveny** [RMacWilliam/permitsadmin#20]
Create api to create and edit vehicle.

On successful save, return new or updated vehicleAndPermits object for the vehicle.

The UI will merge this updated object into local array of vehicles.

Return a response like this:
{
   isSuccessful: true/false,
   errorMessage: "blah blah",
   data: [
     ...new/updated vehicle/permit info
   ]
}

**Comment by RMacWilliam** [comment]
Only returning the single vehicle (and child data) for the updated/added vehicle

**Comment by sarveny** [comment]
Included add/edit api for vehicles in app.

**Comment by sarveny** [comment]
The backend should indicate if there's a validation error with VIN and anything else that's wrong. The current system tells me if I'm using a vin that's already been added to my account.

We can use a response like this: 
{ isSuccessful = false, errorMessage = "Blah blah your vin number already used blah blah", data = null }

**Comment by RMacWilliam** [comment]
Done.

**Comment by sarveny** [comment]
Added alert to dialog if add/edit is unsuccessful with errorMessage.
