### ISSUE TITLE
Create api to return if user has gift cards to redeem

### ISSUE THREAD

**Issue by sarveny** [RMacWilliam/permitsadmin#22]
Create api that indicates if user has redeemable gift cards (based on user token):

Return json data as follows:
{
   seaonalGiftCards: 1,
   classicGiftCards: 2
}

**Comment by RMacWilliam** [comment]
Done. 
asOfDate is an optional parameter, but for now it's ignored - will revisit - currently it will return GC's purchased in the current season (which is the correct behaviour anyway).

**Comment by sarveny** [comment]
Added api to app.
