### ISSUE TITLE
Add isPurchased and isRedeemed fields to Gift Cards object

### ISSUE THREAD

**Issue by sarveny** [RMacWilliam/permitsadmin#24]
Add isPurchased and isRedeemed fields to Gift Cards object.

isPurchased will be true if gift card is purchased, but user can still make changes to name/postal code.
isRedeemed will be true when gift card is purchased. User cannot modify name/postal code anymore.

When isRedeemed is true, then isPurchased must also be true.

**Comment by RMacWilliam** [comment]
These have been added - will confirm which giftcards we want to show - only purchased and unredeemed - not purchased yet?

**Comment by sarveny** [comment]
Added fields to app.
