### ISSUE TITLE
Create new gift cards with tracked shipping included

### ISSUE THREAD

**Issue by sarveny** [RMacWilliam/permitsadmin#28]
Create new gift cards with tracked shipping included to display when purchasing new gift cards.

**Comment by RMacWilliam** [comment]
Done.  Tracked shipping option added for each giftcard to existing endpoint.  Discussion needed around carrying this through to redemption - this part is not done.

**Comment by RMacWilliam** [comment]
Updates for this described in issue 32 - this can be closed I believe.

**Comment by sarveny** [comment]
Problem: Gift cards with and without shipping (ie. Seasonal, Multi-day) have the same productId. The UI needs a unique ID and it's difficult to persist the specific gift card selected to the backend since we don't save with/without tracking info along with productId.

Please create a new UNIQUE id, giftCardId, for each gift card option to persist to the backend.

1. api/giftcard/getavailablegiftcards should return this new giftCardId in the result set.

2. api/giftcard/savegiftcardselectionsforuser should accept giftCardId instead of productId, and the api response should return the new giftCardId.

Input object:
{
    "oVoucherId":"BA1B47DD-57D8-4CE8-9460-5EF6C699A038",  // this is the gift card being updated
	"giftCardId": 1,  // this is the new gift card ID
	"recipientLastName": "Smith",
        "recipientPostal": "L3X0K1"
}

3. api/giftcard/savegiftcardselectionsforuser should return response object with updated selections:

Response object:
{
   "isSuccessful": boolean,
   "errorMessage": string,
   "data": {
        "oVoucherId":"BA1B47DD-57D8-4CE8-9460-5EF6C699A038",
	"giftCardId": 1,
	"recipientLastName": "Smith",
        "recipientPostal": "L3X0K1"
   }
}

**Comment by RMacWilliam** [comment]
Return Object:
{
        "giftcardId": 5,
        "productId": 5,
        "name": "Classic Post Dec 1",
        "displayName": "Classic",
        "frenchDisplayName": "Classique",
        "amount": 205.0000,
        "testAmount": 1.9000,
        "classic": true,
        "isTrackedShipping": false,
        "trackedShippingAmount": 0,
}
