### ISSUE TITLE
Create api to update contact information for user

### ISSUE THREAD

**Issue by sarveny** [RMacWilliam/permitsadmin#29]
Create api to update contact information for user.

Input object should be:
{
addressLine1: string,
addressLine2: string,
city: string,
countryId: string, // This will be CA or US from key/value
email: string,
firstName: string,
initial: string,
lastName: string,
postalCodeId: string,
province: string, // This will be ON, QC, etc. from key/value
telephone: string
}

Return from api should be standard: { isSuccessful, errorMessage, data }. Return updated contact info for data. The same as what gets returned for api/User/getuserdetails

**Comment by RMacWilliam** [comment]
Done, but the email will not be updated - this is more complicated - but everything else should work. SaveUserDetails

**Comment by RMacWilliam** [comment]
Done.
