### ISSUE TITLE
Create api to update account preferences

### ISSUE THREAD

**Issue by sarveny** [RMacWilliam/permitsadmin#30]
Create api to update account preferences.

Input object should be:
{
ofscContactPermission: number, // 0=No, 1=Yes
volunteering: number // 0=No, I am not interested in volunteering, 1=Yes, I already volunteer, 2=Yes, I'd like to volunteer
}

Return from api should be standard: { isSuccessful, errorMessage, data }. Return updated account preferences for data. The same as what gets returned for api/User/getuserpreferences

**Comment by RMacWilliam** [comment]
Done - but some changes coming wrt the rider advantage.  SaveUserPreferences
