### ISSUE TITLE
Create api to create new gift card

### ISSUE THREAD

**Issue by sarveny** [RMacWilliam/permitsadmin#31]
Create api to create new gift card in back-end.

NEEDS TO BE ADDED SO IT WILL BE RETURNED GETGIFTCARDSFORUSER and return object below

Return new gift card object like this (just like from api/giftcard/getavailablegiftcards but only the new gift card):
{
"isSuccessful": boolean,
"errorMessage": string,
"data": {
clubId: null
isPurchased: true
isRedeemed: false
oVoucherId: "ejJzZQ=="
orderId: "21051915001474"
permitId: null
productId: 3  // This id is not unique across tracked/untracked options
purchaserEmail: "[robert.macwilliam@gmail.com](mailto:robert.macwilliam@gmail.com)"
recipientLastName: "Jones"
recipientPostal: "L3X0K1"
redemptionCode: "9ae0e7f122627402"
shippingOption: "0"
transactionDate: "2022-10-16T11:05:08.077"
useShippingAddress: null
giftCardId: "" // This is the unique gift card ID
}
}

**Comment by RMacWilliam** [comment]
A little confused on this - sorry.  I'm returning it now as a single new giftcardSelection.  AddGiftcardForUser - we can discuss if this isn't right.

**Comment by sarveny** [comment]
The object should include giftCardId (since this will be unique).
