### ISSUE TITLE
Add additional fields to getgiftcardsforcurrentseasonforuser

### ISSUE THREAD

**Issue by sarveny** [RMacWilliam/permitsadmin#38]
When receiving purchased and unpurchased gift cards from api/giftcard/getgiftcardsforcurrentseasonforuser, return additional fields for UI rendering:

- giftCardId: number (set to giftcard either with/without tracking)
- classic: boolean (you can use isClassic, but tell me!!)
- isTrackedShipping: boolean
- trackedShippingAmount: number
- amount: number
- displayName: string
- frenchDisplayName: string

**Comment by RMacWilliam** [comment]
GiftcardProductId is the new id that identifies the type of giftcard.  VoucherId should always be fully unique.  Other fields added as written
