### ISSUE TITLE
Create api to fetch list of provinces

### ISSUE THREAD

**Issue by sarveny** [RMacWilliam/permitsadmin#4]
Provinces should be returned as list with following object properties:

export interface IParentKeyValue {
    parent: string;
    key: string;
    value: string;
}

For example:
[
    { parent: "CA", key: "ON", value: "Ontario"},
    { parent: "CA", key: "QC", value: "Quebec" },
    { parent: "US", key: "MI", value: "Michigan" },
    { parent: "US", key: "CA", value: "California" },
    { parent: "OT", key: "MX", value: "Mexico" },
]

**Comment by RMacWilliam** [comment]
Done

**Comment by sarveny** [comment]
Added api to code.
