### ISSUE TITLE
Gift card object fields in object should be consistent

### ISSUE THREAD

**Issue by sarveny** [RMacWilliam/permitsadmin#40]
All gift card api should return entire gift card object fields:

api/Giftcard/getgiftcardsforcurrentseasonforuser
api/Giftcard/addgiftcardforuser (it's okay if fields are null, but still return them)
api/giftcard/savegiftcardselectionsforuser (it's okay if fields are null, but still return them)

Current gift card object fields are:
{
        "giftcardId": 0,
        "oVoucherId": "6UFzZQ==",
        "orderId": "20061611040801",
        "transactionDate": "2022-10-16T11:05:08.077",
        "recipientLastName": "Smith",
        "recipientPostal": "L4G 6N4",
        "redemptionCode": "4ab93470f4ca51c9",
        "purchaserEmail": "robert.macwilliam@gmail.com",
        "productId": 1,
        "isRedeemed": false,
        "isPurchased": true,
        "useShippingAddress": false,
        "shippingOption": "0",
        "clubId": 193,
        "permitId": null
    }

And we are adding the following new fields to this object:

- giftCardId: number (set to giftcard either with/without tracking)
- classic: boolean (you can use isClassic, but tell me!!)
- isTrackedShipping: boolean
- trackedShippingAmount: number
- amount: number
- displayName: string
- frenchDisplayName: string

**Comment by RMacWilliam** [comment]
Now returning the same object for all
classic==>isClassic
