### ISSUE TITLE
Get gift cards api shouldn't return giftcardsIds and productIds that don't exist

### ISSUE THREAD

**Issue by sarveny** [RMacWilliam/permitsadmin#41]
When getting list of purchased and unpurchased gift cards, unpurchased items shouldn't include "giftcardId" and "productId" (from the temp gift card selections table) that don't exist for that point in time.

Meaning, if yesterday I selected giftcardId/productId 1005/5, and today those items don't exist, then clear giftcardId and productid to null before returning from api/Giftcard/getgiftcardsforcurrentseasonforuser

ONLY do this for unpurchased giftcards.

**Comment by RMacWilliam** [comment]
Done, but we need to pass in a date for testing.  If no date is passed, current date is used:

example - getgiftcardsforcurrentseasonforuser?email=robert.macwilliam@gmail.com&asOfDate=2022-10-02 

Optional email and asOfDate
