### ISSUE TITLE
Create api to validate gift cards

### ISSUE THREAD

**Issue by sarveny** [RMacWilliam/permitsadmin#44]
Create api to validate gift card voucher codes.

Input object:
{
   oVehicleId: string,
   redemptionCode: string
{

Response object:
{
   isSuccessful: boolean,
   errorMessage: string,
   data: {
      isValid: boolean,
      message: string
   }
}

If redemption code is invalid then
   return message = API_REDEMPTION_CODE_INVALID and isValid = false
else if redemption code is already redeemed then
   return message = API_REDEMPTION_CODE_REDEEMED and isValid = false
else if redemption code last name doesn't match redeemer's last name then
   return message = API_REDEMPTION_CODE_LAST_NAME_MISMATCH and isValid = false
else if redemption code postal code doesn't match redeemer's postal code then
   return message = API_REDEMPTION_CODE_POSTAL_CODE_MISMATCH and isValid = false
else if redemption code vehicle type (classic, seasonal) doesn't match vehicle type it's being applied to (based on oVehicleId) then
   return message = API_REDEMPTION_CODE_VEHICLE_TYPE_MISMATCH and isValid = false
else
   return message = "" and isValid = true

There may be other business validation required.

**Comment by RMacWilliam** [comment]
Done.  I do catch the situation where BOTH postal code and name mismatch but for now this is returning as API_REDEMPTION_CODE_LAST_NAME_MISMATCH

**Comment by sarveny** [comment]
Can you make this a post method?

**Comment by sarveny** [comment]
I can't seem to get this api to return an expected result.

I'm calling it with the following inputs:
oVehicleId=x+d1ZQ==
redemptionCode=a5d27000406a24e0

And I get the following result:
{
    "isSuccessful": false,
    "errorMessage": "{\"Message\":\"API_UNEXPECTED_ERROR\",\"Code\":null}",
    "data": null
}

The gift card I'm using is: isClassic=false, for recipient: YILDIZ with postal code: L3T7Z1.
The vehicle is: isClassic=false with oVehicleId: x+d1ZQ==

Is it possible that YILDIZ does not match Yildiz (my actual contact info last name)?

**Comment by sarveny** [comment]
Do you think it's become of the weird text in the pdf?

![image](https://github.com/RMacWilliam/permitsadmin/assets/74275116/0856224d-309e-44d6-9af9-f6111f6f7c11)

**Comment by RMacWilliam** [comment]
Will look asap

**Comment by RMacWilliam** [comment]
Updated to Post
Ex:
{
"oVehicleId": "x+d1ZQ==",
"redemptionCode": "a5d27000406a24e0"
}

**Comment by sarveny** [comment]
Validating properly now. But I think we need additional validation. For example, I was able to use a Seasonal Gift Card for a Multi-Day permit. I think you need to validate the type of permit selected for the vehicle, and not allow if it's multi-day. This would result in an API_REDEMPTION_CODE_VEHICLE_TYPE_MISMATCH result.

**Comment by RMacWilliam** [comment]
I just remembered why this probably wasn't in the logic initially - only seasonal/classic permits have the option to apply a giftcard and MD's did not - either way though I'll code a check for this

**Comment by sarveny** [comment]
Done. Also added logic to only display redeem gift card section if vehicle is not multi-day
