### ISSUE TITLE
Update getprovinces to return french labels

### ISSUE THREAD

**Issue by sarveny** [RMacWilliam/permitsadmin#46]
Currently, we only return English labels. Update api to return french labels too.
{
        "parent": "CA",
        "key": "AB",
        "value": "Alberta",
        "valueFr": "Alberta"
    }

CA, AB, Alberta, Alberta
CA, BC, British Columbia, Colombie-Britannique
CA, MB, Manitoba, Manitoba
CA, NB, New Brunswick, Nouveau-Brunswick
CA, NL, Newfoundland and Labrador, Terre-Neuve-et-Labrador
CA, NS, Northwest Territories, Territoires du Nord-Ouest
CA, NT, Nova Scotia, Nouvelle-Écosse
CA, NU, Nunavut, Nunavut
CA, ON, Ontario, Ontario
CA, PE, Prince Edward Island, Île-du-Prince-Édouard
CA, QC, Quebec, Québec
CA, SK, Saskatchewan, Saskatchewan
CA, YT, Yukon, Yukon

For US states, return english and french the same.

**Comment by RMacWilliam** [comment]
Done.
