### ISSUE TITLE
Begin checkout process

### ISSUE THREAD

**Issue by sarveny** [RMacWilliam/permitsadmin#48]
`Here's a first pass on what I think is needed.

We need to know:

Permits:  
oVehicleId, ProductId, Tracked Shipping (bool), RedemptionCode (if applicable), ShippingAddressChoice,  Shipping Address Info (if choice is not primary address)

I can then figure out if the Permit is complete (giftcard that covers tracked shipping selection) - meaning NO further payment is required.  These permits can be created right away and don't need a Moneris Approval.

Giftcards:
ProductId, Lastname, Postal, TrackedShipping (bool)

Giftcards will ALWAYS need to be paid.

This info will be saved with an OrderId in a PreOrder table(s), then the OrderId will come back from Moneris either as Approved or Declined and then the subsequent processing can happen (permits and giftcards get created, receipts emailed), `

**Comment by sarveny** [comment]
Create POST api to generate moneris preload object:

For example:
{
   isSuccessful: boolean,
   errorMessage: string,
   data: {
    "ticket": "1686267509j0AB5fbHx9qtwsUZiiLUplQ0vBXZ5T",
    "orderId": "638218643066942482",
    "environment": "qa",
    "amount": number
   }
}

UI will send following information from checkout:

`
{
   permits: [
      { oVehicleId: string, redemptionCode: string
   ],
   giftCards: [
      { oVoucherId: string }
   ],
   trackedShipping: boolean,
   shippingTo: number, // 0=primary, 1=alternate
   alternateAddress: {
      addressLine1: string,
      addressLine2: string,
      city: string,
      postalCode: string,
      province: string,  // key: ON
      country: string   // key: CA
   }
}
`

**Comment by RMacWilliam** [comment]
First version done - more validations required, but as long as you send valid giftcardProductId's and ProductId's a total should be calculated and returned along with ticket info.  Also confirmed that production tickets are working.  For now though system will remain in test mode.  Prepurchase is saving in DB

**Comment by sarveny** [comment]
When we discussed this, we said that we'd be submitting oVehicleId which contains info about selected permit and date ranges for multi-day permits. And we'd submit oVoucherId which contains info about selected gift card type (seasonal, classic, with/without tracking) and recipient info. Please see object definition above.

**Comment by sarveny** [comment]
{
    "permits": [
        {
            "oVehicleId": "string",
            "redemptionCode": "string",
            "productId": 1,
            "dateStart": "string",
            "dateEnd": "string",
            "clubId": "string"
        },
        {
            "oVehicleId": "string",
            "redemptionCode": "string",
            "productId": 1,
            "dateStart": "string",
            "dateEnd": "string",
            "clubId": "string"
        }
    ],
    "giftCards": [
        {
            "oVoucherId": "string",
            "giftcardProductId": 1,
            "recipientLastname": "string",
            "recipientPostal": "string"
        }
    ],
    "trackedShipping": false,
    "shippingTo": 0,
    "alternateAddress": {
        "addressLine1": "string",
        "addressLine2": "string",
        "city": "string",
        "postalCode": "string",
        "province": "string",
        "country": "string"
    }
}

**Comment by RMacWilliam** [comment]
I think we can close this one

**Comment by sarveny** [comment]
Added language to this object to apply proper UI language for moneris checkout.
