### ISSUE TITLE
Change sendgiftcardpdf api to post method

### ISSUE THREAD

**Issue by sarveny** [RMacWilliam/permitsadmin#49]
Change sendgiftcardpdf api to POST.

Result:
{
   isSuccessful: boolean,
   errorMessage: string,
   data: null
}

**Comment by RMacWilliam** [comment]
Done, but for some reason the API doesn't bind to a simple object like:
{
   "orderId": "2342342342342"
}

But if you post JUST the orderId string "2342342342342",  it works - see api

**Comment by sarveny** [comment]
Weird. Can we fix this?

**Comment by RMacWilliam** [comment]
Works now with standard input.  Postman updated
