### ISSUE TITLE
Update getshippingfees api to return french labels

### ISSUE THREAD

**Issue by sarveny** [RMacWilliam/permitsadmin#50]
Update getshippingfees api to return french labels.

{
   id: string,
   name: string,
   nameFr: string,  // NEW FIELD
   price: number,
   showConfirmation: boolean
}

Untracked should be renamed to Standard, and return french version as "Standard".
For Tracked item, return french version as "Priorité".
For US item, rename to "United States", and return french version as "États-Unis".

**Comment by RMacWilliam** [comment]
Done.
