### ISSUE TITLE
Create logout api to invalidate security token

### ISSUE THREAD

**Issue by sarveny** [RMacWilliam/permitsadmin#51]
Create POST api method to logout user and invalidate security token and possibly cleanup any items that shouldn't be available when the user logs in again (for example, moneris preloads, etc.)

**Comment by RMacWilliam** [comment]
Done.  See Postman LogoutUserProd.  Logout will return standard successerrormessage.  Afterwards, any further api calls should return a 401.  Logging in again is then required.
