### ISSUE TITLE
Calling giftcard/getIsValidRedemptionCodeForVehicle should return tracked shipping amount

### ISSUE THREAD

**Issue by sarveny** [RMacWilliam/permitsadmin#55]
Calling giftcard/getIsValidRedemptionCodeForVehicle should return tracked shipping amount included with the gift card.

Right now we get a response like this:

{
    "isSuccessful": true,
    "errorMessage": "",
    "data": {
        "isValid": true,
        "trackedShippingAmount": number, <------- ADD THIS property (expect value like 10 here)
        "message": null
    }
}

**Comment by RMacWilliam** [comment]
Done,
