### ISSUE TITLE
Gift card pdf has unexpected characters

### ISSUE THREAD

**Issue by sarveny** [RMacWilliam/permitsadmin#56]
![image](https://github.com/RMacWilliam/permitsadmin/assets/74275116/611b4734-ac50-4c39-bf4d-2915f1f700e4)

**Comment by sarveny** [comment]
The [?] should be z characters.

**Comment by sarveny** [comment]
![image](https://github.com/RMacWilliam/permitsadmin/assets/74275116/ac406c73-5166-415c-bcd9-9ce9c50e406f)

**Comment by RMacWilliam** [comment]
Hopefully corrected now.

**Comment by sarveny** [comment]
Looks good from my end.
