### ISSUE TITLE
For api/permit/savePrePurchaseData, allow null values for some optional fields

### ISSUE THREAD

**Issue by sarveny** [RMacWilliam/permitsadmin#63]
Allow null for permits: { redemptionCode, dateStart, dateEnd } since these can have no value.

**Comment by RMacWilliam** [comment]
The dates looked like they were already nullable, but now redemption code is nullable as well.  Tested with below and it worked properly:
{
    "permits": [
        {
            "oVehicleId": "6IF2ZQ==",
            "redemptionCode": null,
            "productId": 5,
            "dateStart": null,
            "dateEnd": null,
            "clubId": 106
        }
    ],
    "trackedShipping": true,
    "shippingTo": 0
}
