### ISSUE TITLE
Handle zero balance transactions

### ISSUE THREAD

**Issue by sarveny** [RMacWilliam/permitsadmin#65]
When cart balance is zero (due to using gift cards to offset purchase amount), send proper response to UI.

**Comment by sarveny** [comment]
When zero or negative balance purchase occurs, then permit/savePrePurchaseData should return amount=0 in the data property.

If amount=0, then page will redirect to Payment Approved.
Otherwise, moneris payment page will be displayed.

**Comment by RMacWilliam** [comment]
Yay!  Working.
