### ISSUE TITLE
Create api to fetch snowmobile clubs

### ISSUE THREAD

**Issue by sarveny** [RMacWilliam/permitsadmin#7]
Array of snowmobile clubs should have following fields:

export interface IKeyValue {
    key: string;
    value: string;
}

* If you need to return other information for clubs, then IKeyValue will not be appropriate, so we'll create a new interface to represent the data.

For example,
[
    { key: "1", value: "Arctic Riders Snow Club" },
    { key: "2", value: "Ontario Snow Club" }
]

**Comment by RMacWilliam** [comment]
Done

**Comment by sarveny** [comment]
Added api to app.
