### ISSUE TITLE
Create post api to verify code returned in account creation email

### ISSUE THREAD

**Issue by sarveny** [RMacWilliam/permitsadmin#70]
Send guid code as input:
{
code: string; // guid
}

Return standard response:
{
isSuccessful: boolean,
errorMessage: string,
data: object
}

Data should contain:
{
isValid?: boolean;
message?: string; // code if not valid
}

API_CONFIRM_ACCOUNT_INVALID_CODE
API_CONFIRM_ACCOUNT_ALREADY_VERIFIED
API_CONFIRM_ACCOUNT_ACCOUNT_NOT_FOUND

**Comment by RMacWilliam** [comment]
Done.  See Postman VerifyAccountProd.

**Comment by sarveny** [comment]
When code is valid, then data object in result object should look like this:
data: { isValid: true, message: "" }

Currently, data object is returning as null for valid codes.

When code is invalid, current result from api is correct, for example:
data: { isValid: false, message: "API_CONFIRM_ACCOUNT_ALREADY_VERIFIED" }

**Comment by RMacWilliam** [comment]
Done.
