### ISSUE TITLE
Add and update properties in api/vehicle/getvehiclesandpermitsforuser

### ISSUE THREAD

**Issue by sarveny** [RMacWilliam/permitsadmin#75]
Update permits and permitOptions objects to have these properties:
isClassic
isSeasonal
isMultiDay
isSpecialEvent (if this is true, then isMultiDay MUST be true as well)

Note: Only one of isClassic, isSeasonal, and isMultiDay can be true at one time!!!

**Comment by RMacWilliam** [comment]
Done.
