### ISSUE TITLE
Disallow login for unverified accounts

### ISSUE THREAD

**Issue by sarveny** [RMacWilliam/permitsadmin#77]
User must verify account through new account email link.

If account is unverified, return errorMessage with string:
API_LOGIN_UNVERIFIED_ACCOUNT
API_LOGIN_INVALID_CREDENTIALS  <-- if username and/or password is invalid

{
  isSuccessful: boolean,
  errorMessage: string,
  data: object
}

Data will have properties:
data: {
email: string,
firstName: string,
initial: string,
isFirstLoginOfSeason: boolean,
isValid: boolean;
lastName: string;
token: string;
message: string; // If isValid is false, set to constant above
}

**Comment by RMacWilliam** [comment]
Done.  See Postman ValidateUserProd for example
