### ISSUE TITLE
Create api to fetch gift card types

### ISSUE THREAD

**Issue by sarveny** [RMacWilliam/permitsadmin#8]
Array of gift cards should have following fields:

export interface IGiftCardOption {
    id: string; // guid
    name: string;
    price: number;
}

For example:
[
    {
        id: "f4305623-bd5c-4c5a-b624-7a82fb21a1b5",
        name: "Seasonal",
        price: 287.5
    },
    {
        id: "b85f91f5-a633-450b-986a-9e2308a53e9f",
        name: "Classic",
        price: 197.5
    }
]

**Comment by RMacWilliam** [comment]
Done - but will return more data - returns the full product data with admin fee already added.

**Comment by sarveny** [comment]
Added api to app.
