### ISSUE TITLE
Create api to fetch purchased gift cards

### ISSUE THREAD

**Issue by sarveny** [RMacWilliam/permitsadmin#9]
Array of gift cards purchased should have the following fields:

export interface IGiftCard {
    id: string; // guid
    giftCardOptionId: string;
    lastName: string;
    postalCode: string;
    isEditable: boolean;
}

This object references the gift card type that was selected when the gift card was purchased (giftCardOptionId).

For example, this gift card is purchased and is not editable (can't change card type) but user can edit last name and postal code:
[
    {
        id: "3347ddc6-b6cc-479e-ab26-920c42383d02",
        giftCardOptionId: "f4305623-bd5c-4c5a-b624-7a82fb21a1b5", // Seasonal
        lastName: "SMITH",
        postalCode: "M5W 1E6",
        isEditable: false
    }
]

**Comment by RMacWilliam** [comment]
Done - There are some extra fields sent back for now, some may be used, but some not - we can discuss/refine.

**Comment by sarveny** [comment]
Added api to app.
