### ISSUE TITLE
Create api to download temporary permit

### ISSUE THREAD

**Issue by sarveny** [RMacWilliam/permitsadmin#90]
Given query parameter "code" (which is oPermitId), download temporary permit.

Include property "isTempPermitAvailable: boolean", and if true, UI will call api and pass code=oPermitId and permit will be downloaded.

Include logic on backend to prevent download if criteria is not met (dec 1, temp permit validity period, etc...)

**Comment by RMacWilliam** [comment]
Completed.  See Postman GetTempPdfForPermitProd. Returns PDF Filestream.
