### ISSUE TITLE
Possible inconsistency in generated documents after purchase

### ISSUE THREAD

**Issue by sarveny** [RMacWilliam/permitsadmin#94]
After purchasing a permit, confirmation email contains download links...

<img width="471" alt="image" src="https://github.com/RMacWilliam/permitsadmin/assets/74275116/7b01e2c6-7982-4864-8a61-e51ce725fef4">

https://permitsapi.azurewebsites.net/api/Documents/createOFSCPDF?reference=VR0bXD9erbNL
https://permitsapi.azurewebsites.net/api/Documents/createMTOPDF?reference=VR0bXD9erbNL

This document does NOT have a trail permit number:

<img width="473" alt="image" src="https://github.com/RMacWilliam/permitsadmin/assets/74275116/a71f9482-fe68-4c20-bb0b-dae37c698325">

But this document DOES have a trail permit number:

<img width="475" alt="image" src="https://github.com/RMacWilliam/permitsadmin/assets/74275116/f3138b2a-2a2d-4efc-bf74-aa7f6551603b">

Should they both have the same permit number on top (OFSC718007)?

**Comment by RMacWilliam** [comment]
Seems odd, but this is how it's supposed to work.  Explanation in Teams

**Comment by sarveny** [comment]
Ok
